<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>RFO — Incident #{{ $incident->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 13px; margin: 18px 0 6px; border-bottom: 1px solid #ccc; padding-bottom: 3px; }
        table { width: 100%; border-collapse: collapse; }
        td, th { padding: 4px 6px; text-align: left; vertical-align: top; }
        table.facts td:first-child { width: 28%; color: #555; }
        table.timeline th { background: #f2f2f2; border-bottom: 1px solid #ccc; }
        table.timeline td { border-bottom: 1px solid #eee; }
        .draft { color: #b45309; font-weight: bold; }
        .muted { color: #666; }
        .text { white-space: pre-wrap; }
    </style>
</head>
<body>
    <h1>Reason for Outage</h1>
    <p class="muted">
        Incident #{{ $incident->id }} — {{ $incident->title }}
        @if ($incident->state->value !== 'closed') <span class="draft">· DRAFT (incident is {{ $incident->state->value }}, not yet closed)</span> @endif
    </p>

    <h2>Summary</h2>
    <table class="facts">
        <tr><td>Severity</td><td>{{ ucfirst($incident->severity->value) }}</td></tr>
        <tr><td>Monitor</td><td>{{ $incident->monitor->name }} ({{ $incident->monitor->type->value }} {{ $incident->monitor->target }}{{ $incident->monitor->port ? ':'.$incident->monitor->port : '' }})</td></tr>
        @if ($incident->circuit)
            <tr><td>Circuit</td><td>{{ $incident->circuit->name }} — {{ $incident->circuit->provider->name }}, ref {{ $incident->circuit->circuit_ref }}
                @if ($incident->circuit->aSite || $incident->circuit->zSite) ({{ $incident->circuit->aSite?->code ?? '?' }} ↔ {{ $incident->circuit->zSite?->code ?? '?' }}) @endif</td></tr>
        @endif
        @if ($incident->provider_ticket) <tr><td>Provider ticket</td><td>{{ $incident->provider_ticket }}</td></tr> @endif
        <tr><td>Detected</td><td>{{ $incident->opened_at->utc()->format('Y-m-d H:i:s') }} UTC</td></tr>
        <tr><td>Acknowledged</td><td>{{ $incident->acknowledged_at ? $incident->acknowledged_at->utc()->format('Y-m-d H:i:s').' UTC ('.\App\Alerts\AlertMessage::duration($incident->timeToAcknowledge()).' after detection)' : '—' }}</td></tr>
        <tr><td>Resolved</td><td>{{ $incident->resolved_at ? $incident->resolved_at->utc()->format('Y-m-d H:i:s').' UTC' : '—' }}</td></tr>
        <tr><td>Total duration</td><td>{{ $incident->resolved_at ? \App\Alerts\AlertMessage::duration($incident->timeToResolve()) : '—' }}</td></tr>
    </table>

    <h2>What happened</h2>
    <p class="text">{{ $incident->rfo_summary ?: 'Not yet written.' }}</p>

    <h2>Root cause</h2>
    <p class="text">{{ $incident->rfo_root_cause ?: 'Not yet written.' }}</p>

    <h2>Corrective action</h2>
    <p class="text">{{ $incident->rfo_corrective_action ?: 'Not yet written.' }}</p>

    <h2>Timeline</h2>
    <table class="timeline">
        <tr><th style="width:24%">Time (UTC)</th><th style="width:22%">Change</th><th style="width:16%">By</th><th>Note</th></tr>
        @foreach ($events as $e)
            <tr>
                <td>{{ $e->created_at->utc()->format('Y-m-d H:i:s') }}</td>
                <td>{{ $e->from_state ? ucfirst($e->from_state->value).' → ' : '' }}{{ ucfirst($e->to_state->value) }}</td>
                <td>{{ $e->user?->name ?? 'System' }}</td>
                <td>{{ $e->note }}</td>
            </tr>
        @endforeach
    </table>

    <p class="muted" style="margin-top:24px">Generated by NetWatch on {{ $generatedAt->utc()->format('Y-m-d H:i') }} UTC.</p>
</body>
</html>
